[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
authors = [
  {email = "thomas@gibfest.dk"},
  {name = "Thomas Steen Rasmussen"}
]

classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "dnspython == 2.7.0",
    "PyYAML == 6.0.1",
    "cryptography == 42.0.8",
    "pid == 3.0.4",
]

description = "The client part of the Certgrinder project"
dynamic = ["version"]
license = {text = "BSD 3-Clause License"}
name = "certgrinder"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
certgrinder = "certgrinder.certgrinder:main"

[project.optional-dependencies]
dev = ["twine == 5.1.0", "pre-commit == 4.0.1", "setuptools-scm == 8.2.0", "build==1.2.2.post1"]
test = ["pytest == 8.3.5", "pytest-cov==6.0.0", "tox == 4.24.2"]
docs = ["Sphinx==8.2.3", "sphinx-rtd-theme==3.0.2", "sphinx-argparse==0.4.0"]

[project.urls]
homepage = "https://github.com/tykling/certgrinder"
documentation = "https://certgrinder.readthedocs.org/"

[tool.setuptools_scm]
root = ".."

[tool.setuptools.packages.find]
exclude = ["man*"]

[tool.pydocstyle]
convention = "google"
match = "client/certgrinder/"
