#!/bin/sh
####################################################
# This file is part of certgrinder.
# The latest version can be found on Github at
# https://github.com/tykling/certgrinder
####################################################

# get CSR from stdin and write to a temp file
STDIN=$(cat)
CSRFILE=$(mktemp)
echo "$STDIN" > $CSRFILE

# are we in testmode? get args from $SSH_ORIGINAL_COMMAND
set -- $SSH_ORIGINAL_COMMAND
if [ "$#" -eq "2" -a "$2" = "test" ]; then
    TEST="--staging"
    MODE="test"
else
    TEST=
    MODE="production"
fi

logger "Wrote $(stat -f%z $CSRFILE) bytes CSR from client $SSH_CLIENT to temp file $CSRFILE (running in $MODE mode)"

# get the directory we are running from
BASEPATH=$(realpath $0 | rev | cut -d "/" -f 2- | rev)

# get a temp filename for the certificate files
FULLCHAINFILE=$(mktemp)
CHAINFILE=$(mktemp)
CERTFILE=$(mktemp)
rm -f $CHAINFILE $FULLCHAINFILE $CERTFILE

# get a temp filename to save any error output from certbot
ERRORFILE=$(mktemp)

# loop over the challenge types
for challenge in dns http; do
    # issue new certificate
    COMMAND="/usr/local/bin/sudo /usr/local/bin/certbot certonly --non-interactive --quiet --rsa-key-size 4096 --authenticator manual --preferred-challenges $challenge --manual-auth-hook ${BASEPATH}/manual-auth-hook --manual-cleanup-hook ${BASEPATH}/manual-cleanup-hook --manual-public-ip-logging-ok --config /usr/local/etc/letsencrypt/letsencrypt.ini --csr $CSRFILE --fullchain-path $FULLCHAINFILE --cert-path $CERTFILE --chain-path $CHAINFILE $TEST"
    logger "Running certbot command: $COMMAND"
    $COMMAND 2> $ERRORFILE
    EXITCODE=$?

    # check certbot exit code
    if [ $EXITCODE -eq 0 ]; then
        logger "Success. Certbot wrote $(stat -f%z $CERTFILE) bytes certificate chain to $CERTFILE - sending to stdout and cleaning up temp files"
        # output full certificate chain to stdout
        cat $FULLCHAINFILE
        break
    else
        logger -s "Failed to get certificate using challenge type $challenge. Certbot exit code was $?. Certbot output was:"
        cat $ERRORFILE | logger -s
    fi
done

# clean up temp files (some of these may not exist if certbot failed for some reason)
rm -f $CSRFILE $CERTFILE $CHAINFILE $FULLCHAINFILE $ERRORFILE

# mirror certbots exitcode
logger "exiting with exit code $EXITCODE"
exit $EXITCODE

