#!/bin/sh

# $CERTBOT_DOMAIN is the domain being authenticated.
# $CERTBOT_VALIDATION is the validation string
# $CERTBOT_TOKEN is the requested filename (for http-01 only)

if [ -z "$CERTBOT_TOKEN" ]; then
        # dns challenge
        echo "unimplemented"
else
        # http challenge
        echo "$CERTBOT_VALIDATION" > "/usr/local/www/letsencrypt-auto/.well-known/acme-challenge/${CERTBOT_TOKEN}"
fi

