---
name: "Certgrinder CI Tests"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install dependencies"
        run: "sudo apt install -y git"
      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: ${{ matrix.python }}
      - name: "Install Tox and codecov"
        run: "pip install tox codecov"
      - name: "Run Tox"
        run: "tox -e py"
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v2"
        with:
         fail_ci_if_error: false
         token: "${{secrets.CODECOV_TOKEN}}"
...
